代码风格、规范、注释更新，不涉及代码逻辑
AHXBXA39/ray_tracking pull request #3
Opened 2023-07-19 15:35 UTC by Zlin-Huang

代码风格、规范、注释更新，不涉及代码逻辑
0. 最重要的, vec的运算符重载要加const,否则摄像机类要拷贝构造一次.
1.优化瓶颈在GetPicture,没来得及做
2.最小权限原则.如果你的函数确定不修改一个类,加const
3. 大驼峰,小驼峰,古希腊风,你可以任选一个,但是同一个代码里不要混用不同风格.如:华为微软代码规范:类名大驼峰,实例名小驼峰.谷歌代码规范要求类变量以m_开头,全局变量以g_开头等.不要突然一个大写又一个小写.  4.不要怕变量名长,要起的有意义,全是一个字母过一段时间你自己都看不懂了
5.将GetPixel从GetPicture中抽象出来.BalMove从main抽象出来.(最好不要有超50行的函数)  6.指出可以改进的点,比如有些地方可以调用C++的库多线程
7.其他

2023-07-19 15:45 UTC, Zlin-Huang commented on light_tracing.cpp
> +    const double pi = acos(-1);
M_PI在有些平台上有问题,还是用acos-1吧,反正O1

2023-07-19 15:48 UTC, Zlin-Huang commented on light_tracing.cpp
> -        for (int i = -60; i <= 60; i++)
代码不变,就continue改成return,然后加一行注释.我注意到可能会有冲突,改了啥请及时修正

2023-07-20 04:25 UTC, littlewhitecloud commented on light_tracing.cpp
> +    const double pi = acos(-1);
使用
`#define _USE_MATH_DEFINES `
可以解决问题

2023-07-20 04:27 UTC, littlewhitecloud commented on light_tracing.cpp
> +            // First todo: remove goto(goto will cause lots of effert.)
```suggestion
            // First todo: remove goto(goto will cause lots of effect.)

```

2023-07-20 04:28 UTC, littlewhitecloud commented on light_tracing.cpp
> +            // First todo: remove goto(goto will cause lots of effert.)
建议TODO大写，effect拼错了

2023-07-20 04:28 UTC, littlewhitecloud commented on light_tracing.cpp
> +        double time = 0; // Todo: it is not a good name, and will error if run days.
```suggestion
        double time = 0; // TODO: it is not a good name, and will error if run days.

```

2023-07-20 04:29 UTC, littlewhitecloud commented on light_tracing.cpp
> +            // Todo: 主线程（渲染线程）整体1秒，而不是主操作完后等一秒。这样渲染效果更佳
```suggestion
            // TODO: 主线程（渲染线程）整体1秒，而不是主操作完后等一秒。这样渲染效果更佳

```

2023-07-20 04:29 UTC, littlewhitecloud commented on light_tracing.cpp
> +        //
```suggestion

```

2023-07-20 04:29 UTC, littlewhitecloud commented on light_tracing.cpp
> +        //
```suggestion
```

2023-07-20 04:29 UTC, littlewhitecloud commented on light_tracing.cpp
> +    // Todo: i and j is not good name. Use wide_pixel height_pixel instead.
```suggestion
    // TODO: i and j is not good name. Use width_pixel height_pixel instead.

```

2023-07-20 04:30 UTC, littlewhitecloud commented on light_tracing.cpp
> +    // Todo: 类名大驼峰,实例名小驼峰
```suggestion
    // TODO: 类名大驼峰,实例名小驼峰

```

2023-07-20 04:30 UTC, littlewhitecloud requested changes
一点点小修改与建议（听不听都没事）

2023-07-20 04:50 UTC, AHXBXA39 commented
okay

2023-07-20 04:50 UTC, merged